//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VisTest.rc
//
#define IDI_VISTEST                     1
#define IDR_MENU                        1
#define IDNEXT                          3
#define IDTIMED                         4
#define IDD_DIALOG1                     101
#define IDD_VISTEST                     101
#define IDR_MENU1                       103
#define IDC_PICSRC                      1000
#define IDC_PICDST                      1002
#define ID_EXIT                         40001
//#define ID_PALETTE                      40002
//#define ID_TRANSFORM                    40003
//#define ID_SHAPE                        40004
#define ID_PALETTE_BASE                 40100
#define ID_TRANSFORM_BASE               40200
#define ID_SHAPE_BASE                   40300
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
