//+----------------------------------------------------------------------------
//
//  This file was generated by ucdtool.exe.
//  DO NOT HAND MODIFY
//
//  Contents: Generated Unicode data classification functions and enumerations
//
//-----------------------------------------------------------------------------

#pragma once

enum UcdProperty;

bool    UcdLookupBooleanProperty(UcdProperty prop, char32_t inputChar) throw();
int32_t UcdLookupEnumeratedProperty(UcdProperty prop, char32_t inputChar) throw();
int32_t UcdLookupValueProperty(UcdProperty prop, char32_t inputChar, int32_t defaultValue) throw();

enum UcdProperty
{
    UcdPropWhiteSpace = 1,
    UcdPropBidiMirrored = 2,
    UcdPropDiacritic = 3,
    UcdPropVariationSelector = 4,
    UcdPropLineBreakClass = 5,
    UcdPropScript = 6,
    UcdPropBidiClass = 7,
    UcdPropGeneralCategory = 8,
    UcdPropMirrorCharacter = 9,
    TotalUcdProps = 10
};

enum WhiteSpace {};

inline bool UcdIsWhiteSpace(char32_t inputChar) throw() {return UcdLookupBooleanProperty(UcdPropWhiteSpace, inputChar);}

enum BidiMirrored {};

inline bool UcdIsBidiMirrored(char32_t inputChar) throw() {return UcdLookupBooleanProperty(UcdPropBidiMirrored, inputChar);}

enum Diacritic {};

inline bool UcdIsDiacritic(char32_t inputChar) throw() {return UcdLookupBooleanProperty(UcdPropDiacritic, inputChar);}

enum VariationSelector {};

inline bool UcdIsVariationSelector(char32_t inputChar) throw() {return UcdLookupBooleanProperty(UcdPropVariationSelector, inputChar);}

enum LineBreakClass
{
    LineBreakClassAI = 0,
    LineBreakClassAL = 1,
    LineBreakClassB2 = 2,
    LineBreakClassBA = 3,
    LineBreakClassBB = 4,
    LineBreakClassBK = 5,
    LineBreakClassCB = 6,
    LineBreakClassCL = 7,
    LineBreakClassCM = 8,
    LineBreakClassCR = 9,
    LineBreakClassEX = 10,
    LineBreakClassGL = 11,
    LineBreakClassH2 = 12,
    LineBreakClassH3 = 13,
    LineBreakClassHY = 14,
    LineBreakClassID = 15,
    LineBreakClassIN = 16,
    LineBreakClassIS = 17,
    LineBreakClassJL = 18,
    LineBreakClassJT = 19,
    LineBreakClassJV = 20,
    LineBreakClassLF = 21,
    LineBreakClassNL = 22,
    LineBreakClassNS = 23,
    LineBreakClassNU = 24,
    LineBreakClassOP = 25,
    LineBreakClassPO = 26,
    LineBreakClassPR = 27,
    LineBreakClassQU = 28,
    LineBreakClassSA = 29,
    LineBreakClassSG = 30,
    LineBreakClassSP = 31,
    LineBreakClassSY = 32,
    LineBreakClassWJ = 33,
    LineBreakClassXX = 34,
    LineBreakClassZW = 35,
    TotalLineBreakClass
};

inline LineBreakClass UcdGetLineBreakClass(char32_t inputChar) throw() {return (LineBreakClass) UcdLookupEnumeratedProperty(UcdPropLineBreakClass, inputChar);}

enum Script
{
    ScriptArabic              = 0,
    ScriptArmenian            = 1,
    ScriptBalinese            = 2,
    ScriptBengali             = 3,
    ScriptBopomofo            = 4,
    ScriptBraille             = 5,
    ScriptBuginese            = 6,
    ScriptBuhid               = 7,
    ScriptCanadian_Aboriginal = 8,
    ScriptCarian              = 9,
    ScriptCham                = 10,
    ScriptCherokee            = 11,
    ScriptCommon              = 12,
    ScriptCoptic              = 13,
    ScriptCuneiform           = 14,
    ScriptCypriot             = 15,
    ScriptCyrillic            = 16,
    ScriptDeseret             = 17,
    ScriptDevanagari          = 18,
    ScriptEthiopic            = 19,
    ScriptGeorgian            = 20,
    ScriptGlagolitic          = 21,
    ScriptGothic              = 22,
    ScriptGreek               = 23,
    ScriptGujarati            = 24,
    ScriptGurmukhi            = 25,
    ScriptHan                 = 26,
    ScriptHangul              = 27,
    ScriptHanunoo             = 28,
    ScriptHebrew              = 29,
    ScriptHiragana            = 30,
    ScriptInherited           = 31,
    ScriptKannada             = 32,
    ScriptKatakana            = 33,
    ScriptKayah_Li            = 34,
    ScriptKharoshthi          = 35,
    ScriptKhmer               = 36,
    ScriptLao                 = 37,
    ScriptLatin               = 38,
    ScriptLepcha              = 39,
    ScriptLimbu               = 40,
    ScriptLinear_B            = 41,
    ScriptLycian              = 42,
    ScriptLydian              = 43,
    ScriptMalayalam           = 44,
    ScriptMongolian           = 45,
    ScriptMyanmar             = 46,
    ScriptNew_Tai_Lue         = 47,
    ScriptNko                 = 48,
    ScriptOgham               = 49,
    ScriptOl_Chiki            = 50,
    ScriptOld_Italic          = 51,
    ScriptOld_Persian         = 52,
    ScriptOriya               = 53,
    ScriptOsmanya             = 54,
    ScriptPhags_Pa            = 55,
    ScriptPhoenician          = 56,
    ScriptRejang              = 57,
    ScriptRunic               = 58,
    ScriptSaurashtra          = 59,
    ScriptShavian             = 60,
    ScriptSinhala             = 61,
    ScriptSundanese           = 62,
    ScriptSyloti_Nagri        = 63,
    ScriptSyriac              = 64,
    ScriptTagalog             = 65,
    ScriptTagbanwa            = 66,
    ScriptTai_Le              = 67,
    ScriptTamil               = 68,
    ScriptTelugu              = 69,
    ScriptThaana              = 70,
    ScriptThai                = 71,
    ScriptTibetan             = 72,
    ScriptTifinagh            = 73,
    ScriptUgaritic            = 74,
    ScriptVai                 = 75,
    ScriptYi                  = 76,
    ScriptZzzz                = 77,
    TotalScript
};

inline Script UcdGetScript(char32_t inputChar) throw() {return (Script) UcdLookupEnumeratedProperty(UcdPropScript, inputChar);}

enum BidiClass
{
    BidiClass_AL  = 0,
    BidiClass_AN  = 1,
    BidiClass_B   = 2,
    BidiClass_BN  = 3,
    BidiClass_CS  = 4,
    BidiClass_EN  = 5,
    BidiClass_ES  = 6,
    BidiClass_ET  = 7,
    BidiClass_L   = 8,
    BidiClass_LRE = 9,
    BidiClass_LRO = 10,
    BidiClass_NSM = 11,
    BidiClass_ON  = 12,
    BidiClass_PDF = 13,
    BidiClass_R   = 14,
    BidiClass_RLE = 15,
    BidiClass_RLO = 16,
    BidiClass_S   = 17,
    BidiClass_WS  = 18,
    TotalBidiClass
};

inline BidiClass UcdGetBidiClass(char32_t inputChar) throw() {return (BidiClass) UcdLookupEnumeratedProperty(UcdPropBidiClass, inputChar);}

enum GeneralCategory
{
    GeneralCategoryCc = 0,
    GeneralCategoryCf = 1,
    GeneralCategoryCn = 2,
    GeneralCategoryCo = 3,
    GeneralCategoryCs = 4,
    GeneralCategoryLl = 5,
    GeneralCategoryLm = 6,
    GeneralCategoryLo = 7,
    GeneralCategoryLt = 8,
    GeneralCategoryLu = 9,
    GeneralCategoryMc = 10,
    GeneralCategoryMe = 11,
    GeneralCategoryMn = 12,
    GeneralCategoryNd = 13,
    GeneralCategoryNl = 14,
    GeneralCategoryNo = 15,
    GeneralCategoryPc = 16,
    GeneralCategoryPd = 17,
    GeneralCategoryPe = 18,
    GeneralCategoryPf = 19,
    GeneralCategoryPi = 20,
    GeneralCategoryPo = 21,
    GeneralCategoryPs = 22,
    GeneralCategorySc = 23,
    GeneralCategorySk = 24,
    GeneralCategorySm = 25,
    GeneralCategorySo = 26,
    GeneralCategoryZl = 27,
    GeneralCategoryZp = 28,
    GeneralCategoryZs = 29,
    TotalGeneralCategory
};

inline GeneralCategory UcdGetGeneralCategory(char32_t inputChar) throw() {return (GeneralCategory) UcdLookupEnumeratedProperty(UcdPropGeneralCategory, inputChar);}

inline int32_t UcdGetMirrorCharacter(char32_t inputChar) throw() {return UcdLookupValueProperty(UcdPropMirrorCharacter, inputChar, inputChar);}

