CLS

  PRINT
  PRINT
  PRINT "                             The Circus of Despair!"
  PRINT
  PRINT "             By Firewalker-911 and That Other Guy, What's His Name?"
  PRINT "                (Even though they probably would never admit it)"
  PRINT
  PRINT

  'Play silly music

 PLAY "MBT160O1L8CDEDCDL4ECCC>"
 FOR i = 1 TO 2
  PLAY "L8EL4EEL8CL4EL2G<G"
   NEXT i
  PRINT "Annoying music, is it not? type 1 :-P"

  INPUT "    Kindly press a key to continue... We're waiting.", Worthless$
'Main Section "M"   At the circus, confronting the Evil Clown
  

CLS
PRINT "   You are at the Circus of Death. The Evil Clown of Horrid Smells stares you"
PRINT "straight in the eye, and says, 'A man armed with a rubber chicken is "
PRINT "threatening you with the tattoo that is on the roof of his mouth that "
PRINT "features a can of beans with the name Gloria on it. What do you do?' "
PRINT "he says. 'WHAT do you do?'"
PRINT "   He reaches for his jelly-blaster. There is a large, old bloodhound "
PRINT "laying on the ground, snoring and drooling, and the tightrope walkers "
PRINT "are going at it in the center ring."
PRINT
PRINT "Your choice:"
PRINT "1. Grab the old dog and throw it at The Evil Clown "
PRINT "   of Horrid Smells."
PRINT
PRINT "2. You tell the clown, ' Look behind you! It's the Battle of Britain!'"
PRINT "   and escape from this red-nosed nightmare to the tightrope."
PRINT
PRINT "3. You try to fight the Evil Clown with your Midy Midy Lighter (TM)."
PRINT
INPUT "Okay. Your pick. 1, 2, or 3? ", Choice$

' 1     Throw the dog

IF Choice$ = "1" THEN
   CLS
   PRINT "   You grab the old, crusty dog by the scruff of its neck and launch it "
   PRINT "at the scary clown. He falls back, but, during all this, the drool from "
   PRINT "the scaggly, old, decrepit bloodhound drips on the evil fiend, and he begins "
   PRINT "to melt."
   PRINT "   Lying upon the dusty ground is the former-clown's former "
   PRINT "weapon-of-destruction: a Yikes! (TM) Jelly Blaster (TM)."
   PRINT "   Okay, Bub. Your choice. (Think fast! Those unbathed carnies "
   PRINT "over there are eyeing you suspiciously!)"
   PRINT
   PRINT "1. You pick up the Yikes! (TM) Jelly Blaster (TM), "
   PRINT "   and aim it in a threatening manner."
   PRINT
   PRINT "2. Forget the friggin' Jelly Blaster! Those carnies are sure "
   PRINT "   coming fast, and, boy! they're REALLY rank. I mean it, man. They "
   PRINT "   smell like like raw sewage or something else equally offensive "
   PRINT "   to your sensitive olfactory senses. Ug."
   PRINT
   PRINT "3. Or pick your nose! (Gadzooks! There's some major blockage up there.)"
   PRINT
   INPUT "Well... What shall it be? 1, 2, or 3? ", Choice1$
  
   ' 1.1        Get the gun!

   IF Choice1$ = "1" THEN
      CLS
      PRINT "You deftly swipe the Jelly Blaster. You see that it has two triggers, one "
      PRINT "at each end of the marvelously-crafted weapon. You look at yourself sitting "
      PRINT "there gaping open-mouthed at the computer screen looking rather perplexed, "
      PRINT "and ask yourself pleadingly, 'Which one do I pull? Help me please!'"
   END IF

   '1.2         Run like bloody heck!

   IF Choice1$ = "2" THEN
      CLS
      PRINT "   What good would a green slime-covered Jelly Blaster do you now? Those "
      PRINT "carnies are getting ever closer; in addition to that, they don't look "
      PRINT "very amicable today. You take off like a cat scrambling out of a hot "
      PRINT "oven, making sure not to slip over the puddle of ooze that was once your "
      PRINT "arch enemy and bolt off in the direction of tightropes and begin "
      PRINT "ascending the ladder to the top. Fear grips you by the throat as "
      PRINT "you look down from the vertiginous height. You can see your house "
      PRINT "from here. You suppress the urge to hurl."
   END IF

   '1.3         Pick your nose?

   IF Choice1$ = "3" THEN
      CLS
      PRINT "Okay, you blithering idiot: you insert your index finger up your right "
      PRINT "nostril and, um... well, you get the picture. After many dextrous maneuvers "
      PRINT "you decide to cease and desist, as those rotten carnies have encircled you. "
      PRINT "Their beady stares drill holes into your very soul. "
   END IF

END IF  ' END of Choice 1 branching from main

IF Choice$ = "2" THEN
     CLS
     PRINT "   You scream at the top of your lungs, 'Look behind you! It's your mother! "
     PRINT "Aggh!' As the Fiendish Clown is screaming in terror and mortal fear, you "
     PRINT "bolt off in the direction of tightropes and begin ascending the ladder to "
     PRINT "the top. Fear grips you by the throat as you look down from the vertiginous "
     PRINT "height. You can see your house from here. You suppress the urge to hurl."
     PRINT "   The wicked-looking carnies are begining to climb up the ladder after you "
     PRINT "You hightail it to the top. You see here a jumbo-size, 90 lb. jar of butter "
     PRINT "(Julio the tightrope-walker must have left it here for alter consumption), "
     PRINT "and the beginning of the tightrope."
     PRINT
     PRINT "What next?"
     PRINT "1. You empty the butter jar on the ladder."
     PRINT
     PRINT "2. You happily ingest the jar of butter. Mmmmmmm?"
     INPUT "Your wish is my command, master.", Choice2$
 
     IF Choice2$ = "1" THEN
       CLS
       PRINT "Okay. You just dumped the butter all over the ladder. The carnies, "
       PRINT "unable to maintain their grip on the slick ropes, begin to drop like "
       PRINT "flys. You clever thing, you! You climb down on the rope and"
       PRINT "make it down just in time to meet the crazy, none-too-overjoyed carnies "
       PRINT "as they unpile."
     END IF
END IF          ' END of 2 branching from Main

IF Choice$ = "3" THEN
       CLS
       PRINT "   You jump toward the rank-smelling clown, furiously flicking at your "
       PRINT "Midy Lighter, and the clown, in defense, opens his giant maw and belches "
       PRINT "an evil-smelling belch in your general direction. You scream in abject "
       PRINT "terror as you fly into his mouth and are swallowed down his slimy, pickled "
       PRINT "throat."
       PRINT "   You sit there in the dark for a few minutes, scratching your head, utterly "
       PRINT "dumbfounded. You light your lighter. This is not a very safe-looking place: you "
       PRINT "are in the clown's acerbic stomach, bubbling in gastro-intestinal acid."
       PRINT "   Good God, Jim! What will you do?"
END IF          'End of 3 branching from main

