// pgfxoptions.h - Plain Options
//
// **If you are sharing this library with other projects,
//   Do not edit this file. Instead, copy it to your project
//   folder and edit that version. Be sure you update the
//   project options to include your project's path in
//   additional include folders.
//
// This file contains user options that customize the compile. It is included
// before any other headers so that definitions will be recognized.
// It's useful for reducing code bloat or enabling features not on by default.

//#undef PlainIncludeMMX	// do not include MMX code in compile
#define PlainIncludeMMX 1	// include MMX code in compile
