x = 62, y = 8, rule = B35678/S5678
bbo3bobo7bobo5bobo8bobo5bobo7bobo3bo$boobobobobobobobobobobobobobo4bob
oboboboboboboboboboboboboo$62o$62o$62o$62o$boobobobobobobobobobobobobo
bo4boboboboboboboboboboboboboboo$bbo3bobo7bobo5bobo8bobo5bobo7bobo3bo!
The spacefiller by David I. Bell
The spacefiller is constructed with two David's Eppstein c/7
spaceships.
This pattern finally answered the question about whether Diamoeba
objects can grow forever. It also won David a $50 prize for that fact.
