x = 123, y = 7, rule = B3678/S34678
4bo18bo18bo43bo15bo15bo$4b3o14b5o14b3o43b3o11b5o11b3o$bob3obo13b5o13bo
b3obo37bob3obo10b5o10bob3obo$oob5o12b7o12b5oboo35boob5o9b7o9b5oboo$bob
3obo13b5o13bob3obo37bob3obo10b5o10bob3obo$4b3o14b5o14b3o43b3o11b5o11b  
3o$4bo18bo18bo43bo15bo15bo!
This shows two ways in which a white dwarf left over from a nova explosion
can be re-ignited by two p32 ships to form a new nova.  The white dwarf
remains, and so the reaction can be repeated with more ships.
David I. Bell, May 1997
