x = 79, y = 14, rule = B3678/S34678
75b3o$77boo$$bbobo$bbobo35boob4o$3ob3o12boo10bobo5bob4ob3o$bb3o12b6ob
3o4bob3o4b8obo$bb3o12b10o3b8obb9obo$18b11obob19o$bb3o12b10o3b8obb9obo$
bb3o12b6ob3o4bob3o4b8obo$3ob3o12boo10bobo5bob4ob3o$bbobo35boob4o$bbobo
!
A reaction in which a period 16 oscillator can turn a rocket into a
period 260 puffer which generates sets of four p16 oscillators.
This is a reaction which can be the basis of a breeder.
David I. Bell, May 1997
