x = 10, y = 49, rule = B3678/S34678
bboo$bobobo$b3obo$boo$b3o$bbo$oobo$3o$3bo$bo$boo$bo$bo$3bo$6o$4obo$bo
bbo$bboo3$4boboo$3b5o$bb6o$b8o$10o$b8o$bb6o$3b5o$4boboo3$bboo$bobbo$4o
bo$6o$3bo$bo$bo$boo$bo$3bo$3o$oobo$bbo$b3o$boo$b3obo$bobobo$bboo!
A wickstretcher which leaves a thick "pillar" behind it.
This is composed of a period 40 spaceship found by Nathan Thompson
which is perturbed by the sparks from two period 4 spaceships.
David I. Bell, April 1997
