//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by lanmole.rc
//

#define ProgClass L"PknLanFileMole"
#define ProgVersion L"1.2"
#define ProgTitle L"FileMole " ProgVersion L" (Alpha/ßeta)"
#define ProgDate L"2003-09-01"
#define ProgWebpage L"http://fdwr.tripod.com/"
#define ProgEmail L"fdwr@hotmail.com"
#define ProgHelpFile L"FileMole.txt"
#define ProgIcq L"#139423993"

#define IdFileStop						2
#define IDAPPLY                         3
#define IDC_LISTHEADER                  101
#define IDC_LANLIST                     102
#define IDC_LANPATH                     103
#define IDC_PATH                        103
#define IDC_TOOLBAR                     104
#define IDC_STATUSBAR                   105
#define IDD_FILTERS                     106
#define IDS_ABOUT                       107
#define IDD_SCAN_FILTERS                108
#define ID_SCAN_FILTERS                 108
#define IDC_SIZEPANEL                   110
#define IDC_SIZELOG                     111
#define IDD_INFO                        112
#define IDI_FILE_UNKNOWN                117
#define IDI_SERVER_OUT                  118
#define IDI_COPYFILES                   122
#define IDI_QUEUE                       122
#define IDI_FILTERFILES                 123
#define IDI_WORKGROUPL                  124
#define IDI_RENAME                      125
#define IDB_TOOLBAR                     129
#define IDD_ABOUT                       140
#define IDI_DELETE_WARN                 143
#define IDI_PROPERTIES_S                144
#define IDI_DELETE                      145
#define IDI_GOTO_LEFT                   146
#define IDI_GOTO_RIGHT                  147
#define IDI_GOTO_UP                     148
#define IDB_LANLIST                     152
#define IDB_LANLIST4B                   155
#define IDI_PROPERTIES                  156
#define IDI_PROPS                       156
#define IDI_FIND                        157
#define IDI_VIEW                        158
#define IDI_FAVS                        159
#define IDC_WEBPAGE                     1018
#define IDC_EMAIL                       1019
#define IDC_README                      1020
#define IDD_DELETE_WARN                 1025
#define IDC_USEFILTER                   1032
#define IDC_FILTERFILES                 1033
#define IDC_CAPITALMIXED                1034
#define IDC_LOG                         1035
#define IDC_CLEAR                       1037
#define IDC_CUSTOM3                     1045
#define IDC_BUTTON1                     1047
#define IDC_VERSION                     1049
#define IDC_ATRLIST                     1052
#define IDC_HAND                        32649
#define ID_RENAME                       40001
#define ID_FIND                         40002
#define ID_GOTO                         40003
#define ID_TEST                         40003
#define ID_COPY                         40004
#define ID_EDIT_DELETE                  40005
#define ID_OPEN                         40006
#define ID_FILE_OPEN                    40006
#define ID_EXPLORE                      40007
#define ID_FILE_EXPLORE                 40007
#define ID_PROPS                        40008
#define ID_NEWSCAN                      40009
#define ID_REFRESH                      40009
#define ID_CLEAR                        40010
#define ID_MASK                         40011
#define ID_EXCLUDE                      40011
#define ID_FILTER_EXCLUDE               40011
#define IdFilterExclude                 40011
#define ID_TREE                         40012
#define ID_LIST                         40013
#define ID_ROOT_NETWORK                 40014
#define ID_ROOT_SERVER                  40015
#define ID_ROOT_FILE                    40016
#define ID_ORDER_FOLDERS                40017
#define IdOrderContainers               40017
#define IdOrderName                     40018
#define IdOrderSize                     40020
#define IdOrderDate                     40022
#define IdOrderNewest                   40023
#define ID_SELECT_SINGLE                40024
#define ID_SELECT_ALL                   40025
#define ID_SELECT_NONE                  40026
#define ID_FILE_OPTIONS                 40027
#define ID_ORDER_INCLUDED               40028
#define ID_SELECT_STATIC                40029
#define ID_DETAILS                      40030
#define ID_INCLUDE                      40031
#define IdFilterInclude                 40031
#define ID_FILTER                       40032
#define ID_STOP                         40033
#define ID_PAUSE                        40033
#define ID_SELECT_INVERT                40039
#define ID_SELECT_MATCH                 40040
#define ID_SELECT_FIND                  40040
#define IdSelectFind                    40040
#define ID_SELECT_REMATCH               40041
#define ID_VIEW_NAME                    40043
#define ID_LOAD_LIST                    40048
#define ID_LOAD_TREE                    40048
#define ID_STORE_LIST                   40049
#define ID_STORE_TREE                   40049
#define ID_EXPORT_LIST                  40050
#define ID_EXPORT_TREE                  40050
#define ID_MAINWND                      40051
#define ID_LOGON                        40053
#define ID_LOGOFF                       40054
#define ID_BROWSENET                    40056
#define ID_SHOW_EMPTY                   40057
#define IdViewEmpty                     40057
#define IDC_VIEW_OPTIONS                40058
#define ID_ACTION_DELETEITEM            40067
#define ID_ACTION_QUEUE                 40068
#define ID_ACTION_COPY                  40069
#define ID_ACTION_STOP                  40070
#define IdOrderNone                     40071
#define ID_ROOT_SHARE                   40072
#define ID_FILE_FIND                    40073
#define ID_FILE_GOTO                    40074
#define ID_FILE_COPY                    40075
#define IDC_FILE_FILTER                 40076
#define ID_FILE_PROPERTIES              40077
#define ID_FILE_QUEUE                   40080
#define ID_SHELL_OPEN                   40081
#define ID_SHELL_PLAY                   40082
#define IDC_VIEW_FILTER                 40083
#define IDC_VIEW_FILTERS                40083
#define ID_VIEW_FILTERS                 40083
#define ID_VIEW_FINDS                   40084
#define ID_VIEW_GOTO                    40085
#define ID_VIEW_FAVS                    40085
#define ID_VIEW_TREE                    40086
#define ID_VIEW_LIST                    40087
#define ID_VIEW_QUEUE                   40088
#define ID_VIEW_PROPERTIES              40089
#define ID_VIEW_SCAN_OPTIONS            40090
#define ID_VIEW_SCAN                    40090
#define ID_SCAN_CLEARDELETEDFILES       40092
#define ID_SCAN_CLEAROLDSERVERS         40094
#define IdListExpand                    40095
#define IdListCollapse                  40096
#define ID_SELECT_NEWFILES              40097
#define ID_HELP_README                  40099
#define IdFileDelete                    40100
#define ID_ACTION_MOVEUP                40101
#define ID_ACTION_MOVEDOWN              40102
#define ID_ACTION_MOVETOP               40103
#define ID_ACTION_MOVEBOTTOM            40105
#define ID_ACTION_FINDSELECT            40106
#define ID_ACTION_GOTO                  40108
#define ID_ACTION_ADDTOGOTO             40109
#define ID_FILE_REFRESH                 40110
#define ID_SCAN_CLEARNEWFLAG            40111
#define IdClearNewFlag                  40111
#define ID_TOOLS_SENDLANMESSAGE         40112
#define ID_TOOLS_SCANIPRANGE            40113
#define ID_TOOLS_CRACK9XSERVERPASS      40114
#define ID_TREE_INFO                    40119
#define ID_HELP_TIPPOINTER              40123
#define ID_HELP_ABOUT                   40124
#define ID_EDIT_COPYNAMES               40125
#define ID_EDIT_COPYFILES               40126
#define ID_EDIT_PASTEFILES              40127
#define ID_EDIT_COPYFULLNAMES           40128
#define IdEditCopyPathsNames            40128
#define IdEditCopyPaths                 40128
#define ID_GOTO_ADDFAVORITE             40129
#define IdFileAddFav                    40129
#define IdGoto1                         40131
#define IdGoto2                         40132
#define IdGoto3                         40133
#define IdGoto4                         40134
#define IdGoto5                         40135
#define IdGoto6                         40136
#define IdGoto7                         40137
#define IdGoto8                         40138
#define IdGoto9                         40139
#define IdGoto10                        40140
#define IdGoto11                        40141
#define IdGoto12                        40142
#define IdGoto13                        40143
#define IdGoto14                        40144
#define IdGoto15                        40145
#define IdGoto16                        40146
#define IdGoto17                        40147
#define IdGoto18                        40148
#define IdGoto19                        40149
#define IdGoto20                        40150
#define IdGotoForward                   40151
#define IdGotoBackward                  40152
#define ID_VIEW_PROPS                   40154
#define IdGotoIn                        40156
#define IdGotoOut                       40157
#define IdListExpandAll                 40158
#define IdListCollapseAll               40159
///#define ID_FILE                         40161
#define IdFileCopy                      40163
#define IdFileQueue                     40164
#define IdFileFind                      40165
#define IdFileStart                     40166
#define IdFileRefresh                   40167
#define IdFileOpen                      40168
#define IdFileExplore                   40169
#define IdFileProps                     40170
#define IdSelectSingle                  40171
#define IdSelectAll                     40172
#define IdSelectNone                    40173
#define IdSelectInvert                  40174
#define IdSelectNew                     40175
#define IdEditCopy                      40176
#define IdEditCopyNames                 40177
#define IdEditPaste                     40178
#define IdEditDelete                    40179
#define IdClearSelected                 40179
#define IdViewFavs                      40180
#define IdGotoRoot                      40181
#define IdGotoHome                      40182
#define IdGotoPrevious                  40183
#define IdGotoNext                      40184
#define IdViewOptions                   40185
#define IdViewFinds                     40186
#define IdViewScan                      40187
#define IdViewHistory                   40188
#define IdViewQueue                     40190
#define IdViewProps                     40191
#define IdViewTree                      40192
#define IdViewListRecursive             40193
#define IdViewHelp                      40194
#define IdViewList                      40195
#define IdListLoad                      40196
#define IdListStore                     40197
#define IdListExport                    40198
#define IdListImport                    40199
#define IdClearDeleted                  40200
#define IdClearOldServers               40201
#define IdClearNewFileFlag              40202
#define IdClearAll                      40203
#define IdClearFinished                 40204
#define IdViewLog                       40205
#define IdViewPanel                     40206
#define IdViewStatBar                   40207
#define IdViewToolBar                   40208
#define IdToolsSendLanMsg               40209
#define IdToolScanIpRange               40210
#define IdToolsCrack9xPass              40211
#define IdHelpTipPointer                40212
#define IdHelpReadme                    40213
#define IdHelpAbout                     40214
#define IdViewFont                      40215
#define IdViewFilters                   40216
#define IdHeirarchyPath					40217
#define IdQueuePath						40218
#define IdQueuePathDesktop				40219
#define IdListDefaultFile				40220
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         40216
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
