// pgfxoptions.h - Plain Graphics Options
//
// * Do NOT edit this file
// * Instead, copy it to your project folder and edit that version.
// * (this is just a template/placeholder).
//
// This file contains user options that customize the compile. It is included
// before any other headers so that definitions will be recognized.

#ifndef pgfxoptions_h
#define pgfxoptions_h

//#undef PlainUseMMX	// do not include MMX code in compile
#define PlainUseMMX 1	// include MMX code in compile

#define PlainUseCursor

#endif
