//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RANDOS.rc
//
#define IDC_TARGET_NAME                 101
#define IDD_MAIN                        101
#define IDC_TARGET_IP                   102
#define IDC_ATTACK_TYPE                 103
#define IDI_MAIN                        103
#define IDC_STATUS                      200

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
