//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DirField.rc
//
#define IDR_MENU                        1
#define IDI_DIRFIELD                    1
#define IDC_DIFEQU                      101
#define IDC_DIRFIELD                    102
#define IDC_STATUSBAR                   103
#define ID_VIEW_TICKS                   40001
#define ID_VIEW_REDRAW                  40002
#define ID_VIEW_SHOWTICKS               40003
#define ID_EDIT_EQUATION                40004
#define ID_EDIT_INSERTLAYER             40005
#define ID_EDIT_DELETELAYER             40006
#define ID_HELP                         40008
#define ID_FILE_LOAD                    40009
#define ID_FILE_SAVE                    40010
#define ID_FILE_EXIT                    40011
#define ID_VIEW_RANGES                  40015
#define ID_VIEW_ALLLAYERS               40016
#define ID_VIEW_CURRENTLAYER            40017
#define ID_VIEW_HIDELAYER               40018
#define ID_FILE_SAVEIMAGE               40019
#define ID_EDIT_CLEARALL                40020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40021
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
