#pragma once
// *** This file is generated. Rerun the tool instead of editing it ***

namespace DWritEx
{

enum UnicodeCategory
{
    UnicodeCategoryCc = 0,
    UnicodeCategoryCf = 1,
    UnicodeCategoryCn = 2,
    UnicodeCategoryCo = 3,
    UnicodeCategoryCs = 4,
    UnicodeCategoryLl = 5,
    UnicodeCategoryLm = 6,
    UnicodeCategoryLo = 7,
    UnicodeCategoryLt = 8,
    UnicodeCategoryLu = 9,
    UnicodeCategoryMc = 10,
    UnicodeCategoryMe = 11,
    UnicodeCategoryMn = 12,
    UnicodeCategoryNd = 13,
    UnicodeCategoryNl = 14,
    UnicodeCategoryNo = 15,
    UnicodeCategoryPc = 16,
    UnicodeCategoryPd = 17,
    UnicodeCategoryPe = 18,
    UnicodeCategoryPf = 19,
    UnicodeCategoryPi = 20,
    UnicodeCategoryPo = 21,
    UnicodeCategoryPs = 22,
    UnicodeCategorySc = 23,
    UnicodeCategorySk = 24,
    UnicodeCategorySm = 25,
    UnicodeCategorySo = 26,
    UnicodeCategoryZl = 27,
    UnicodeCategoryZp = 28,
    UnicodeCategoryZs = 29,
    UnicodeCategoryTotal,
    UnicodeCategoryForceDword = 0x7FFFFFFF,
};

enum UnicodeScript
{
    UnicodeScriptArabic              = 0,
    UnicodeScriptArmenian            = 1,
    UnicodeScriptBalinese            = 2,
    UnicodeScriptBengali             = 3,
    UnicodeScriptBopomofo            = 4,
    UnicodeScriptBraille             = 5,
    UnicodeScriptBuginese            = 6,
    UnicodeScriptBuhid               = 7,
    UnicodeScriptCanadian_Aboriginal = 8,
    UnicodeScriptCarian              = 9,
    UnicodeScriptCham                = 10,
    UnicodeScriptCherokee            = 11,
    UnicodeScriptCommon              = 12,
    UnicodeScriptCoptic              = 13,
    UnicodeScriptCuneiform           = 14,
    UnicodeScriptCypriot             = 15,
    UnicodeScriptCyrillic            = 16,
    UnicodeScriptDeseret             = 17,
    UnicodeScriptDevanagari          = 18,
    UnicodeScriptEthiopic            = 19,
    UnicodeScriptGeorgian            = 20,
    UnicodeScriptGlagolitic          = 21,
    UnicodeScriptGothic              = 22,
    UnicodeScriptGreek               = 23,
    UnicodeScriptGujarati            = 24,
    UnicodeScriptGurmukhi            = 25,
    UnicodeScriptHan                 = 26,
    UnicodeScriptHangul              = 27,
    UnicodeScriptHanunoo             = 28,
    UnicodeScriptHebrew              = 29,
    UnicodeScriptHiragana            = 30,
    UnicodeScriptInherited           = 31,
    UnicodeScriptKannada             = 32,
    UnicodeScriptKatakana            = 33,
    UnicodeScriptKayah_Li            = 34,
    UnicodeScriptKharoshthi          = 35,
    UnicodeScriptKhmer               = 36,
    UnicodeScriptLao                 = 37,
    UnicodeScriptLatin               = 38,
    UnicodeScriptLepcha              = 39,
    UnicodeScriptLimbu               = 40,
    UnicodeScriptLinear_B            = 41,
    UnicodeScriptLycian              = 42,
    UnicodeScriptLydian              = 43,
    UnicodeScriptMalayalam           = 44,
    UnicodeScriptMongolian           = 45,
    UnicodeScriptMyanmar             = 46,
    UnicodeScriptNew_Tai_Lue         = 47,
    UnicodeScriptNko                 = 48,
    UnicodeScriptOgham               = 49,
    UnicodeScriptOl_Chiki            = 50,
    UnicodeScriptOld_Italic          = 51,
    UnicodeScriptOld_Persian         = 52,
    UnicodeScriptOriya               = 53,
    UnicodeScriptOsmanya             = 54,
    UnicodeScriptPhags_Pa            = 55,
    UnicodeScriptPhoenician          = 56,
    UnicodeScriptRejang              = 57,
    UnicodeScriptRunic               = 58,
    UnicodeScriptSaurashtra          = 59,
    UnicodeScriptShavian             = 60,
    UnicodeScriptSinhala             = 61,
    UnicodeScriptSundanese           = 62,
    UnicodeScriptSyloti_Nagri        = 63,
    UnicodeScriptSyriac              = 64,
    UnicodeScriptTagalog             = 65,
    UnicodeScriptTagbanwa            = 66,
    UnicodeScriptTai_Le              = 67,
    UnicodeScriptTamil               = 68,
    UnicodeScriptTelugu              = 69,
    UnicodeScriptThaana              = 70,
    UnicodeScriptThai                = 71,
    UnicodeScriptTibetan             = 72,
    UnicodeScriptTifinagh            = 73,
    UnicodeScriptUgaritic            = 74,
    UnicodeScriptVai                 = 75,
    UnicodeScriptYi                  = 76,
    UnicodeScriptZzzz                = 77,
    UnicodeScriptTotal
    UnicodeScriptForceDword          = 0x7FFFFFFF,
};

} // namespace DWritEx
