// guioptions.h - Plain UI Options
//
// * Do NOT edit this file
// * Instead, copy it to your project folder and edit that version.
// * (this is just a template/placeholder).
//
// This file contains user options that customize the compile. It is included
// before any other headers so that definitions will be recognized.

#ifndef guioptions_h
#define guioptions_h

#define PlainUseWindow
#define PlainUseRootWindow
#define PlainUseTitleBar
#define PlainUseWindowBg
#define PlainUsePreview
#define PlainUseBorder
#define PlainUseButton
#endif
