//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ctest.rc
//
#define IDI_CTEST                       1
#define IDM_CTEST                       1
#define IDOK2                           2
#define IDOK3                           3
#define IDD_CTEST_DIALOG                102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDC_CTEST                       109
#define IDR_MAINFRAME                   128
#define IDR_BG                          130
#define IDR_FG                          131
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
