! "main" (cells 38 length 9 width 36 generation 0)
! Period 30 glider gun.
! First object found whose population grows to infinity.
! Bill Gosper, around 1970.
7k18h@!
.............O
............OOOO
...........OO.O........OO
OO........OOO.O.O......O..O
O..........OO.O............O
............OOOO...........O......OO
.............O.............O.......O
.......................O..O
.......................OO
