//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pknft.rc
//
#define IdiMain                         1
#define IdrMain                         1
#define IdcRefresh                      6
#define IddMain                         101
#define IddFile                         102
#define IddFiles                        102
#define IddChat                         103
#define IddAudio                        104
#define IddAbout                        105
#define IdcAddress                      1000
#define IdcPort                         1001
#define IdcLocalFiles                   1002
#define IdcRemoteFiles                  1003
#define IdcUser                         1004
#define IdcRemoteFiles2                 1004
#define IdcPass                         1005
#define IdcLocalProgress                1006
#define IdcRemoteProgress               1007
#define IdcConnect                      1008
#define IdcLocalProgress2               1008
#define IdcListen                       1009
#define IdcDisconnect                   1010
#define IdcGet                          1011
#define IdcPut                          1012
#define IdcVerify                       1013
#define IdcGetOptions                   1013
#define IdcPut2                         1014
#define IdcPut3                         1015
#define IdcAbout                        1016
#define IdcPutOptions                   1016
#define IdcLocalPath                    1017
#define IdcRemotePath                   1018
#define IdcLog                          1019
#define IdcLog2                         1020
#define IdcMsg                          1022
#define IdcClipboard                    1027
#define IDC_RICHEDIT21                  1027
#define IdcFiles                        1028
#define IdcAudio                        1029
#define IdcChat                         1030
#define IdcVideo                        1031
#define IdmEditCopy                     40014
#define IdmEditPaste                    40015
#define IdmChatSend                     40016
#define IdmAudioListen                  40017
#define IdmAudioRecord                  40018
#define IdcExit                         40020
#define IdcSend                         40021
#define IdmHelpReadme                   40024

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40025
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
