//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CardGame.rc
//
#define IDC_0                           100
#define IDC_1                           101
#define IDC_2                           102
#define IDC_3                           103
#define IDC_CURSORHAND                  105
#define IDT_PBET                        200
#define IDT_OBET                        201

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
