; Standard Library - system macros
; by Gaz Jones
; https://web.archive.org/web/20030211000714/http://www.phoenix.gb.net:80/x86/
;
%ifndef _SYSTEM_MACROS

%define _SYSTEM_MACROS

%macro AtExit 1
	push	dword %1
	call	_mysystem_atexit_2
	lea	esp,[esp + 4]
%define _MYSYSTEM_ATEXIT_MACRO
%endmacro

%macro Exit 0
	call	_mysystem_exit_2
%define _MYSYSTEM_EXIT_MACRO
%endmacro

%endif
