//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TILEMOLE.rc
//
#define ID_WIDTH_DECREASE               101
#define ID_WIDTH_INCREASE               102
#define ID_HEIGHT_DECREASE              103
#define IDB_TOOLBAR                     103
#define ID_HEIGHT_INCREASE              104
#define ID_TILE_BACK                    105
#define ID_TILE_FORWARD                 106
#define ID_ROW_BACK                     107
#define ID_ROW_FORWARD                  108
#define ID_BYTE_BACK                    109
#define ID_BYTE_FORWARD                 110
#define ID_PAGE_BACK                    111
#define ID_PAGE_FORWARD                 112
#define IDC_STATUSBAR                   113
#define IDC_TOOLBAR                     114
#define IDC_TOOLBOX                     115
#define ID_FILE_NEW                     40001
#define ID_FILE_OPEN                    40002
#define ID_FILE_CLOSE                   40003
#define ID_FILE_REOPEN                  40004
#define ID_FILE_CLOSEALL                40005
#define ID_FILE_SAVE                    40006
#define ID_FILE_SAVEAS                  40007
#define ID_FILE_SAVEALL                 40008
#define ID_FILE_EXIT                    40009
#define ID_EDIT_UNDO                    40010
#define ID_EDIT_REDO                    40011
#define ID_EDIT_CUT                     40012
#define ID_EDIT_COPY                    40013
#define ID_EDIT_PASTE                   40014
#define ID_EDIT_CLEAR                   40015
#define ID_EDIT_SELECTALL               40016
#define ID_EDIT_COPYTO                  40017
#define ID_EDIT_PASTEFROM               40018
#define ID_VIEW_CODEC                   40019
#define ID_VIEW_ROWINTERLEAVED          40023
#define ID_VIEW_BLOCKGRID               40025
#define ID_VIEW_TILEGRID                40026
#define ID_VIEW_PIXELGRID               40027
#define ID_VIEW_STATUSBAR               40028
#define ID_VIEW_TOOLBAR                 40029
#define ID_IMAGE_MIRROR                 40030
#define ID_IMAGE_FLIP                   40031
#define ID_IMAGE_ROTATERIGHT            40032
#define ID_IMAGE_ROTATELEFT             40033
#define ID_IMAGE_SHIFTLEFT              40034
#define ID_IMAGE_SHIFTRIGHT             40035
#define ID_IMAGE_SHIFTUP                40036
#define ID_IMAGE_SHIFTDOWN              40037
#define ID_IMAGE_CANVASSIZE             40038
#define ID_IMAGE_STRECH                 40039
#define ID_NAVIGATE_GOTO                40040
#define ID_NAVIGATE_GOTOAGAIN           40041
#define ID_NAVIGATE_ADDTOBOOKMARKS      40042
#define ID_NAVIGATE_ADDBOOKMARK         40042
#define ID_NAVIGATE_ORGANIZEBOOKMARKS   40043
#define ID_PALETTE_EDITCOLORS           40044
#define ID_PALETTE_SIZE                 40048
#define ID_PALETTE_NEW                  40049
#define ID_PALETTE_ADDTOPALETTES        40051
#define ID_PALETTE_ORGANIZEPALETTES     40052
#define ID_VIEW_ZOOM_IN                 40053
#define ID_VIEW_ZOOM_OUT                40054
#define ID_VIEW_ZOOM_100                40055
#define ID_VIEW_ZOOM_200                40056
#define ID_VIEW_ZOOM_400                40057
#define ID_VIEW_ZOOM_800                40058
#define ID_VIEW_ZOOM_1600               40059
#define ID_VIEW_ZOOM_3200               40060
#define ID_VIEW_MODE_1DIMENSIONAL       40061
#define ID_VIEW_MODE_2DIMENSIONAL       40062
#define ID_VIEW_BLOCKSIZE_FULLCANVAS    40063
#define ID_VIEW_BLOCKSIZE_CUSTOM        40064
#define ID_PALETTE_BYTEORDER_INTEL      40065
#define ID_PALETTE_BYTEORDER_MOTOROLA   40066
#define ID_PALETTE_IMPORTFROM_THISFILE  40067
#define ID_PALETTE_IMPORTFROM_ANOTHERFILE 40068
#define ID_WINDOW_NEWWINDOW             40069
#define ID_WINDOW_NEW                   40069
#define ID_WINDOW_TILE                  40070
#define ID_WINDOW_CASCADE               40071
#define ID_WINDOW_ARRANGEICONS          40072
#define ID_WINDOW_ARRANGE               40072
#define ID_HELP_HELPTOPICS              40073
#define ID_HELP_TIPOFTHEMILLENIUM       40074
#define ID_HELP_ABOUTTILEMOLESTER       40075
#define ID_PALETTE_FORMAT_BGR555        40076
#define ID_PALETTE_FORMAT_RGB888        40077
#define ID_PALETTE_FORMAT_NES           40078
#define ID_PALETTE_FORMAT_EGA           40079

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40080
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
