//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UnUhs.rc
//
#define IDD_UNUHS                       101
#define IDR_UNUHS                       102
#define IDI_UNUHS                       103
#define IDC_UhsText                     1000
#define ID_OPEN                         40001
#define ID_COPY                         40002
#define ID_SAVE                         40003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
