//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by EFOF.rc
//
#define IDI_EFOF                        1
#define IDNEXT                          3
#define IDTIMED                         4
#define IDADDPOINT                      5
#define IDDELETEPOINT                   6
#define IDMOVEPOINT                     7
#define IDD_DIALOG1                     101
#define IDD_EFOF                        101
#define IDC_PICSRC                      1000
#define IDC_PICDST                      1002
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
