x = 52, y = 52, rule = B36/S23
bb3o$bobbo$o3bo$obbo$3o3b3o$5bobbo$4bo3bo$4bobbo$4b3o3b3o$9bobbo$8bo3b
o$8bobbo$8b3o12$26b3o$25bobbo$24bo3bo$24bobbo$24b3o20$50boo$50boo$48b
oo$48boo!
This is an aperiodic puffer which produces occasional pairs of blinkers
and a biloaf.  The output is the same as a period 96 puffer, but this
puffer does not have a period, and the intervals between output grows.
The puffer itself grows in size.
Dean Hickerson, 1994
