x = 57, y = 23, rule = B36/S23
21bo$19b3o$18bo$18boo$$55boo$55bo$16bo36bobo$15b3o35boo$15bobo$15b3o5$
35boo$oo33bo$bo31bobo$bobo23bo5boo7b3o$bboo23bo15bobo$8boo15boobo15boo
$7boboo16bo17bo$8boo17bo!
This is a period 144 glider gun which produces gliders in the irregular
pattern 101110, where a 1 represents a glider and a 0 represents a "hole".
This results from impacting a replicator against a period 24 glider gun.
In general, it is not known what patterns are possible using these methods.
Dean Hickerson, 1994
