x = 22, y = 7, rule = B36/S23
8boo$8bobobobo$8boo$bboo14boo$bobo14bobo$bo18bo$oo18boo!
This is a small period 24 oscillator that is formed from a "shuttle"
and two eaters which stabilize it.  By itself, the shuttle creates a
flipped copy of itself (with some junk) in 12 generations, but the junk
then destroys it.  Adding eaters as shown inhibits the junk and turns it
into an oscillator.  The shuttle occurs naturally but usually self-destructs.
Dean Hickerson, 1994
