x = 49, y = 38, rule = B36/S23
21bo$19b3o$18bo$18boo7$16bo$15bobo$14bo3bo$15bobo29boo$15b3o29bo$35boo
8bobo$oo33bo9boo$bo31bobo$bobo29boo$bboo19boo$11b3o9bobobobo$11boboo8b
oo$11b3o$20bo15b3o$21bo14bobbo$19b3o14bo3bo$37bobbo$32b3o3b3o$32bobbo$
26bo5bo3bo$27bo5bobbo$25b3o6b3o4$32bo$33bo$31b3o!
A period 48 glider gun.
This uses a period 24 glider gun and a replicator oscillator which
deletes every other glider.
Dean Hickerson, 1994
