x = 37, y = 27, rule = B36/S23
oo$oo$14bo$13b3o$12booboo$11booboo$10booboo$11b3o$12bo10$25boo6boo$24b
obo6boo$26bo$$35bo$33bobo$34bobo$25boo7bo$25boo!
A period 96 replicator based glider gun.
A block perturbs the replicator to produce the glider, while a period 2
"clock" oscillator prevents a spark from being formed that would modify
the block.  One glider is shown where it was just created.
This is the smallest known glider gun based on replicators.
David I. Bell, 1994
