x = 40, y = 40, rule = B36/S23
bb3o$bobbo$o3bo$obbo$3o3b3o$5bobbo$4bo3bo$4bobbo$4b3o4$14b3o$13bobbo$
12bo3bo$12bobbo$12b3o3b3o$17bobbo$16bo3bo$16bobbo$16b3o4$26b3o$25bobbo
$24bo3bo$24bobbo$24b3o4$34b3o$33bobbo$32bo3bo$32bobbo$32b3o3boo$38boo$
36boo$36boo!
This is a period 96 puffer which generates a pair of blinkers and a biloaf
every period.  This is constructed by reacting replicators against a beacon.
Dean Hickerson, 1994
