x = 27, y = 27, rule = B36/S23
b3o$o$o$o4$13bo$13bo$13bo5$17bo$16boo$15bobo$14b3o6$24b3o$23bobo$23boo
$23bo!
This is two replicators playing "tug of war" with a blinker.
Here the blinker gets pulled arbitrarily far in both directions.
For N > 6, in generation 2^N the blinker is pulled about 2^(N-3)/3 units
diagonally (to the upper left if N is odd, to the lower right if N is even).
Dean Hickerson, 1994
